apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: website-nuxt
          image: prokip/website:production
          imagePullPolicy: Always
          ports:
            - containerPort: 3000