apiVersion: v1
kind: Service
metadata:
  name: website-service
  # namespace: test
  labels:
    app: website-service
spec:
  selector:
    app: website-service
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000   # It is listening on port 80 so I changed it  